# Generated by Django 6.0.4 on 2026-04-20 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('название_услуги', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название услуги')),
                ('описание', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('цена', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена')),
                ('изображение', models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Изображение')),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='settings/logo', verbose_name='логотип')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('telegram', models.URLField(blank=True, null=True, verbose_name='Telegram')),
                ('whatsapp', models.URLField(blank=True, null=True, verbose_name='WhatsApp')),
                ('youtube', models.URLField(blank=True, null=True, verbose_name='YouTube')),
            ],
        ),
    ]
