# Generated by Django 6.0.4 on 2026-04-20 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='описание',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='изображение',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='название_услуги',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='цена',
            new_name='price',
        ),
    ]
